### ISSUE TITLE
two bugs found in form-validation.js

### ISSUE THREAD

**Issue by Juanse7793** [Tadesse-Alemayehu/Portfolio#17]
https://github.com/Tadesse-Alemayehu/Portfolio/blob/7700ebc5c4db44f2d0d9c2d2d3e05c243f3a04b7/scripts/form-validation.js#L86

Hi Tadesee, maybe you can put a curly brace at the end of the function in order to fix this.

https://github.com/Tadesse-Alemayehu/Portfolio/blob/7700ebc5c4db44f2d0d9c2d2d3e05c243f3a04b7/scripts/form-validation.js#L77

and the 2nd bug is here, in order to fix this you can put the arrow function '=>'.

**Comment by Tadesse-Alemayehu** [comment]
# @Juanse7793 Thanks for the bug report. 
- I have fixed the issue in a commit [d7f1ad5](https://github.com/Tadesse-Alemayehu/Portfolio/pull/18/commits/d7f1ad580cf2e0c68ab2b790b8c92e2f03e18a00). 
- Feel free to review and raise more issues.
