### ISSUE TITLE
Peer Review | Add projects to portfolio

### ISSUE THREAD

**Issue by Retky** [Tadesse-Alemayehu/Portfolio#21]
Your work is going very well 🔥 
### To highlight 
- Well organized ✔️
- Code easy to read ✔️
- Very good use of JavaScript for adding projects ✔️

**Comment by Retky** [comment]
### Can be Improve
- I kindly suggest you could edit the images to have the same aspect ratio; I'll recommend it to be 4:3 is more close for your design requirements
- I think your `.vscode` folder & `package` files could be add to the `.gitignore` list.

**Comment by isaacpitwa** [comment]
**Hi @Tadesse-Alemayehu  👋🏿** 

Good job so far!
There are some improvement points that you may work on to go to  better your project but you are all good  🏅 

## Highlights
- You added  inline comments ✔️ 
-  Utilized the "Review changes" feature from GitHub ✔️ 
- Made comments friendly using emojis ✔️ 
-
## Required changes ♻️ 
- [README] You could improve your instructions for local development set up by adding Commands for the cloning to running the application on a local machine in your [ReadMe](https://github.com/Tadesse-Alemayehu/Portfolio/tree/feature#readme).
- Mobile popup, could be improved by preventing user scroll when a popup is showing ..one way to do this is using CSS style `position: Fixed`


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @isaacpitwa.

**Kindly add all other comments as inline comments this helps the summary be easy to read and they can always go back to the inline comments to fix required changes**

You can also add how the student can reach you on slack or by tagging you in their questions

**Comment by Tadesse-Alemayehu** [comment]
### Hello @Retky @Alexr16 @isaacpitwa
--- 
#### Issue has been fixed. check https://github.com/Tadesse-Alemayehu/Portfolio/pull/22 pull request for a review, and please do let me know if anything needs to be improved.
