### ISSUE TITLE
Review on Desktop version of Tadesse

### ISSUE THREAD

**Issue by chidiebereojingwa** [Tadesse-Alemayehu/Portfolio#6]
## Suggestion by Chidiebere
- Adding media query to each and every section tag 

## Suggestion by Retky
- I like that the size is fixed for both versions
-  I think it will be more efficient to separate the Desktop css code in a diferent file.

## Suggestion by Catherine
- I think that it will be better to have only one header
- You can exclude the different contents of the desktop or mobile using display: none in your css

**Comment by Tadesse-Alemayehu** [comment]
@chidiebereojingwa Thank you for the dubmission guys. this issue is closed on 72da6c4c69f2c1052568243ab95d5ec629e3d2f8 commit hash.
